### PR TITLE
Fix Google ShapeFactory dist. traveled calculation

### LINKED ISSUE #123: Fix Google Shape Factory distance traveled calculation

### PR DESCRIPTION
**Pull request by wingsofovnia**
Fixes #123

### CODE REVIEW

File: backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java [hunk 1]
```diff
@@ -40,50 +48,65 @@ public GoogleMapsShapeFactory(String apiKey) {
...
-                val distanceFromOrigin = localDistance.add(shapePoints.get(i).getDistanceTraveled());
-                shapePoints.add(new ShapePoint(pointLocation, distanceFromOrigin));
-            }
-            chunkNumber += LOCATIONS_LIMIT - 1;
-        } while (chunkNumber < waypoints.size() - 2);
+        val googleReadyWaypoints = notEmpty(waypoints).stream()
+            .map(l -> new LatLng(l.getLatitude(), l.getLongitude()))
+            .toArray(LatLng[]::new);
+
+        List<ShapePoint> shapePoints = calculateDistanceTraveled(googleReadyWaypoints).stream()
```
Comment (glasierr) [inline backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java]: val instead of List?

**Review by glasierr — APPROVED** [review]

File: backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java (hunk 1 above)
Comment (wingsofovnia) [reply backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java]: unfortunately, lombok cant handle this :(
Error:(61, 26) java: incompatible types: java.util.List<java.lang.Object> cannot be converted to java.util.Collection<eu.socialedge.hermes.backend.transit.domain.ShapePoint>

File: backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java [hunk 2]
```diff
@@ -64,45 +62,79 @@ public Shape create(List<Location> waypoints) {
...
+            val originDestDistance = Quantities.getQuantity(originDestDistanceRaw, METRE);
+
+            pathDistances.put(Pair.of(originLatLng, destLatLng), originDestDistance);
+        }
+
+        return pathDistances;
+    }
+
+    private DistanceMatrix calculateDistanceMatrix(LatLng[] origins, LatLng[] destinations) {
+        if (origins.length >= LOCATIONS_LIMIT)
```
Comment (glasierr) [inline backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java]: I don't think you need to do such check in your private method. The only way this condition will be true - is a mistake in your code and such cases should be covered in unit tests

File: backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java [hunk 3]
```diff
@@ -48,12 +46,12 @@ public GoogleMapsShapeFactory(String apiKey) {
...
     @Override
     public Shape create(List<Location> waypoints) {
-        val googleReadyWaypoints = notEmpty(waypoints).stream()
+        val waypointsLatLng = notEmpty(waypoints).stream()
             .map(l -> new LatLng(l.getLatitude(), l.getLongitude()))
             .toArray(LatLng[]::new);
 
-        List<ShapePoint> shapePoints = calculateDistanceTraveled(googleReadyWaypoints).stream()
-            .map(latLngDistTraveled -> {
+        List<ShapePoint> shapePoints = calculatePathDistanceTraveled(waypointsLatLng)
```
Comment (glasierr) [inline backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java]: Why don't you use val everywhere?

**Review by glasierr — CHANGES_REQUESTED** [review]

File: backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java (hunk 3 above)
Comment (wingsofovnia) [reply backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java]: Check previous comment:
unfortunately, lombok cant understand what type is here. It makes List<java.lang.Object> instead of ShapePoint.

Error:(61, 26) java: incompatible types: java.util.List<java.lang.Object> cannot be converted to java.util.Collection<eu.socialedge.hermes.backend.transit.domain.ShapePoint>

File: backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java (hunk 2 above)
Comment (wingsofovnia) [reply backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/GoogleMapsShapeFactory.java]: I'm not sure the thought "if it's private method I should assume it will receive valid data". Mistake in a code that calls a private method is an exceptional situation too, like ArrayOutOfTheBoundException or ArithmeticException. It's better to fail fast here for invalid request instead of wasting API calls imho.

**Review by glasierr — APPROVED** [review]
